Leaderboard: hit the API
WilhelmK109/leaderboard-app pull request #2
Opened 2023-03-09 22:14 UTC by WilhelmK109

### In this milestone, I did the following:
- Created a new game with the name of my choice by using the API.
- Implemented the "Refresh" button that will get all scores for a game.
- Implemented the form "Submit" button that will save a score for a game.
- Used async and await JavaScript features to consume the API.

2023-03-09 22:57 UTC, vickymarz requested changes
Hi @WilhelmK109, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the Git Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-09 22:57 UTC, vickymarz commented on src/index.js
> +      refreshBtn.click();
- [ ] KIndly remove the` refreshBtn` function you added after making the post request. Please note that when the post request is made, it shouldn't also fetch the data and display it on the UI. The data should only be displayed when you click on the refresh button 👍🏽

2023-03-09 22:57 UTC, vickymarz commented on src/index.js
> +    // console.error(error);
- [ ] Kindly remove all commented code from your codebase to make our code clean and readable 👍🏽

2023-03-10 00:47 UTC, franclobo approved these changes
Hi @WilhelmK109, 

# STATUS: APPROVED 😃 

![git-merge](https://user-images.githubusercontent.com/58642949/224193939-c444caa2-b0d1-4fdd-979e-57ee7a60074c.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- No linter errors ✔️ 
- App works as expected 💯 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-10 00:50 UTC, merged